### PR TITLE
profile/list: show errors in table listing instead of failing

### PR DESCRIPTION
**Pull request by dhowden**
Without annotation the error is not helpful when you have multiple profiles.

Note: this also uses the AdminAPIKey, which might need another change to amend.

### CODE REVIEW

**Comment by dhowden** [comment]
FYI @helenamariano this from our conversation.

**Comment by clemfromspace** [comment]
Thanks for the PR @dhowden 👍 

What do you think about gracefully failing, like displaying the error for the profile in the `NB OF INDICES` column instead?
So we can, at the same time:
- See all profiles for which the API credentials are correct (just display the number of indices)
- See all profiles for which the API credentials are not correct (wrong AppID and/or APIKey)
- See all profiles for which we are missing the `listIndices` ACL (like displaying a `? (APIKey without `listIndices` ACL)`)

I'm happy to take over the PR if you don't have the time, let me know :)

**Comment by dhowden** [comment]
Hey @clemfromspace.

No worries, I've updated the change to put the error in the table as suggested.  Happy for you to take it from here to get it over the line!

**Review by clemfromspace — APPROVED** [review]
Looks good 👍

**Pull request merged**
